Murder Player Feature
std-nullptr/AmongUsMenu pull request #97
Opened 2020-12-15 15:32 UTC by manianac

Supports murdering as an imposter
Kill cooldown is respected, button is hidden until kills are allowed

2020-12-15 15:43 UTC, OsOmE1 requested changes
Change the way you get the kill cooldown

2020-12-15 16:35 UTC, manianac commented
Updated to use LocalPlayer::KillTimer

2020-12-15 17:00 UTC, manianac reviewed
Updated to use killtimer

2020-12-16 12:02 UTC, RealMVC approved these changes

2020-12-16 12:06 UTC, OsOmE1 requested changes

2020-12-16 12:06 UTC, OsOmE1 commented on appdata/il2cpp-translations.h
> +	{ {"", "KillButtonManager"}, {"", "MLPJGKEACMM"} },
Remove this translation because you don't use it.

2020-12-16 12:20 UTC, OsOmE1 approved these changes

2020-12-16 12:22 UTC, merged